[env]
TERM = "xterm-256color"

[font]
size = 17

[font.normal]
family = "FiraCode Nerd Font"

[general]
import = [
  "~/.config/alacritty/themes/themes/dracula.toml"
]

[window]
decorations = "Buttonless"

opacity = 0.7
blur = true
